### PR TITLE
Add rollIn animation

### PR DESCRIPTION
**Pull request by satrun77**
Thanks for the script. Here is a minor contribution developed while working on one of my personal projects.

Add animation to roll in. Ported from Animate.css.

```
<div data-sr="rollIn left"> Roll in from left </div>
<div data-sr="rollIn right"> Roll in from right </div>
<div data-sr="rollIn top"> Roll in from top </div>
<div data-sr="rollIn bottom"> Roll in from bottom </div>
```

### CODE REVIEW

**Comment by HybridSolutions** [comment]
@satrun77,

Instead of porting animation effects one by one, can it be done like I'm suggesting here?
https://github.com/julianlloyd/scrollReveal.js/issues/120

**Comment by julianlloyd** [comment]
Thanks @satrun77 

I need a little more time to decide how to proceed, but @HybridSolutions raises a good point — it makes the most sense to add support for the entire library, instead of one by one.

**Comment by satrun77** [comment]
I agree. It would be nice to support the entire Animate.css library.

**Comment by julianlloyd** [comment]
Until this is figured out, I’m working on a rotation keyword for the next minor update; I’m thinking something like…
```html
<div data-sr="enter left, move 50px and roll 30deg"> Foo </div>
```
One thing that comes up, is that if I want to include 3d rotation (i.e. support pitch and yaw as well), rotation would be the first with 3 different keywords for 1 transformation. To illustrate the problem:
```html
// if support for the other 2 axis were added…
<div data-sr="scale down 10% and pitch 15deg"> Foo </div>
<div data-sr="move 10px down and yaw 180deg, with reset"> Foo </div>

// but then what type of rotation does 'hustle' imply?
<div data-sr="hustle 30deg, with reset"> Bar </div>
```

**Comment by satrun77** [comment]
It is nice idea to have different rotation keyword based on the direction.

I may have misunderstood you, but it should be possible to have the rotation and hustle in the same statement. I have created a demo page: http://scrollreveal.my.geek.nz/ that demonstrate using the new keywords with/without ease-in-out and with hustle.

The script is modified to include the 3 keywords that are used to generate the rotate3d property.

Animation with hustle:
```html
<div data-sr="enter left, move 200px and hustle 50px pitch -120"> Foo </div>
```

Also, it is possible to simulate the rollIn animation with something like:
```html
<div data-sr="enter left and move 300px, with pitch -120, over 1s"> Bar </div>
```

Would this be a good option?

**Comment by julianlloyd** [comment]
This looks awesome @satrun77! :beers: 

Do you want to add these changes to your PR, so I can take a closer look?

**Comment by satrun77** [comment]
I have updated PR with the new changes.

**Comment by julianlloyd** [comment]
I’ve created a new branch [v2.2.x-WIP](https://github.com/julianlloyd/scrollReveal.js/tree/v2.2.x-WIP) with your changes. I’ll do a little work on it, and we’ll get this merged into master.

Thanks again for this @satrun77

**Comment by julianlloyd** [comment]
I’ve created a new branch [v2.2.x-WIP](https://github.com/julianlloyd/scrollReveal.js/tree/v2.2.x-WIP) with your changes. I’ve got a little work to do on it for the v2.2.0 release, but this is awesome.

Thanks again for this @satrun77

**Comment by satrun77** [comment]
Thanks @julianlloyd for accepting my PR :smile: :beers:. My Twitter username is @satrun77

**Comment by julianlloyd** [comment]
Hey @satrun77 

Just pinging you to let you know I’m getting close to releasing `v2.2.0`, which includes your PR. Check out the changes I made, I’ve added support for multiple axes—for example:
```html
<div data-sr="wait 0.2s, roll 45deg, flip -90deg"> Foo </div>
<div data-sr="wait 0.4s, roll 30deg, flip -60deg"> Bar </div>
<div data-sr="wait 0.6s, roll 15deg, flip -30deg"> Baz </div>
```
Thanks again!
:beers:

**Comment by satrun77** [comment]
Looks good :)

**Pull request closed without merging**
